### PR TITLE
Add option: export for rmarkdown

### PR DESCRIPTION
**Pull request by yun-j**
With HUGO_EXPORT_RMARKDOWN t, one can export an org file into rmarkdown file. Then, Blogdown can render it to evaluate codes and present results (graphs, tables, etc.) accordingly.

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Hello,

First of all, many thanks for contributing your work to this project. 

I have few points before we can proceed with merging this PR:

1. The contribution is significant. So before I merge it, all the authors (I see 2 authors involved in your PR) need to have copyright assigned to FSF. See https://ox-hugo.scripter.co/doc/contributing-guide/. If you do not want to do that, or cannot, I can suggest some alternative. 
2. From what I understand, RMarkdown is not parsed by Blackfriday, right? If so, the RMarkdown code would better suite in a new `ox-rmarkdown.el` file. You can then of course extend `ox-rmarkdown` from `ox-blackfriday` and override or add the exporter functions. As an example see how `ox-blackfriday` extends `ox-md`. Then instead if an Org keyword to set RMarkdown exporter, you can instead have a defvar. That will make it easier for the RMarkdown users to set it just once in their ox-hugo config. Do you see a scenario where users might have some files rendered by Blackfriday and some in RMarkdown?

**Comment by yun-j** [comment]
Hi,

1. The two authors are all me. I lost log-in access to one Github account (Jonghyun-Yun), so I made PR from my new account (yun-j).
2. I will look into the suggestion. I edited files last year, and have to catch up what I did.

Best,
Jonghyun

Kaushal Modi <notifications@github.com> writes:

> Hello,
>
> First of all, many thanks for contributing your work to this project. 
>
> I have few points before we can proceed with merging this PR:
>
> 1. The contribution is significant. So before I merge it, all the authors (I see 2 authors involved in your PR) need to have copyright assigned to FSF. See https://ox-hugo.scripter.co/doc/contributing-guide/. If you do not want to do that, or cannot, I can suggest some alternative. 
> 2. From what I understand, RMarkdown is not parsed by Blackfriday, right? If so, the RMarkdown code would better suite in a new `ox-rmarkdown.el` file. You can then of course extend `ox-rmarkdown` from `ox-blackfriday` and override or add the exporter functions. As an example see how `ox-blackfriday` extends `ox-md`. Then instead if an Org keyword to set RMarkdown exporter, you can instead have a defvar. That will make it easier for the RMarkdown users to set it just once in their ox-hugo config. Do you see a scenario where users might have some files rendered by Blackfriday and some in RMarkdown? 


-- 
Jonghyun Yun
204 Glenwood Dr. Mansfield TX 76063

**Comment by yun-j** [comment]
Now I remember things clearer. The below is workflow related to the exporter.

org file -> (ox-hugo) -> rmarkdown file -> (blogdown) -> markdown -> (Hugo (Blackfriday)) -> html

Rmarkdown file should follow Blackfriday markdown format except those for 1) source block and 2) inline source. Thus, I made changes on org-blackfriday-src-block and org-blackfriday-inline-src-block, accordingly.

Since the exporter heavily depends on ox-blackfriday.el, I don't know if it's a good idea to have ox-rmarkdown.el.

**Comment by kaushalmodi** [comment]
Hello, apologies for closing this PR because:

1. I do not have the bandwidth to maintain rmarkdown related changes, especially because I don't use it.
2. Please feel free to to fork this repo and maintain that as a separate exporter.

**Pull request closed without merging**
