### PR TITLE
Add a new example site

### PR DESCRIPTION
**Pull request by takaxp**
Hi!

I'm a new ox-hugo user. It's really easy and nice to generate my blog. Thanks!

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Awesome! Hey, our paths meet again! I've been enjoying your `org-tree-slide` package :)

Now that you know about this package, and if you are interested, you can convert org-tree-slide's documentation to Org and publish it using Hugo (examples: doc sites for ox-hugo and use-package).

**Comment by kaushalmodi** [comment]
> And I'm really interested in ox-hugo because the workflow for exporting blog entries is actually suitable for me. I'll try to convert my docs of org-tree-slide to Hugo website as you suggested, and also to apply ox-hugo to my init.org. 

Great! Let me know if you face any issues or find any bugs :)

> Furthermore, I'll learn more about ox-hugo and Hugo itself to integrate some external information like Amazon's affiliate links. It requires some implementations as Hugo shortcodes... but it's really fun for me.

I prefer not to write Hugo shortcodes. That way the Org document stays more portable (example: you can export the same Org document used for your Hugo sites for general export using ox-html or ox-latex too).

I instead prefer to use the Org Special Blocks. See [this as an example][1]. That test exports to [this][2]. I need to stop being lazy and write documentation for it: https://github.com/kaushalmodi/ox-hugo/issues/126 (*I see that you have already voted for that* :)).

> BTW, I actually drive @orgmode_bot account in Twitter so feel free to mention the account when you want to advertise ox-hugo for all Orgers in the world :)

Awesome! I did not know that it was you! :D How does the bot work? Do I need to add `@orgmode_bot` to my tweets? Or just tagging `#OrgMode` would work? 

---

Also, are you on Mastodon? I am `@kaushalmodi@mastodon.technology` there.


[1]: https://github.com/kaushalmodi/ox-hugo/blame/master/test/site/content-org/all-posts.org#L3916-L3921
[2]: https://ox-hugo.scripter.co/test/posts/alert-short-code-lookalike/

**Comment by kaushalmodi** [comment]
> OK, I understand. I think I can write an emacs lisp to check the duplication in an org buffer and call it before exporting the subtrees to warn the duplication.

If you have your copyright assigned to FSF, PR to ox-hugo for this would be welcome!

  
> Here is my example. Exported a single a-test-of-duplicate.md file will be placed in ~/content/2019 directory. 

I understand when the file overwrites can happen. I didn't understand a real use case where this can happen.. Also, in your example you have section as 2018, so posts should go in `contents/2018`.

How about this?

```org
#+hugo_base_dir: ../

* 2018
:PROPERTIES:
:EXPORT_HUGO_SECTION: 2018
:END:
** DONE the original entry
   CLOSED: [2018-08-24 Fri 19:06]
:PROPERTIES:
:EXPORT_FILE_NAME: a-test-of-duplicate
:END:

post 1


* 2019
:PROPERTIES:
:EXPORT_HUGO_SECTION: 2019
:END:
** DONE a new entry
   CLOSED: [2018-08-24 Fri 19:07]
:PROPERTIES:
:EXPORT_FILE_NAME: a-test-of-duplicate
:END:

post 2
```

Now the files won't get overwritten:
- content/2018/a-test-of-duplicate.md
- content/2019/a-test-of-duplicate.md

> I like to refresh my entries annually so next year I'll create a new org file as 2019.org :)

I may not have understood your actual use case yet. When you say "refresh my entries annually", you mean to update the posts at the same place? Or put them in a new `content/2019` directory?

If it's the latter, my above example should work (i.e. just update the HUGO_SECTION), and you won't have duplicates.

**Comment by takaxp** [comment]
> If you have your copyright assigned to FSF, PR to ox-hugo for this would be welcome!

Yes. I have the sign. I'll try to write a moudle!

>> Here is my example. Exported a single a-test-of-duplicate.md file will be placed in ~/content/2019 directory.

Really sorry, that's typo. I meant it was `~/content/2018`.

For this year, I'll put all my posts as subtrees in `2018.org` under `content-org` directory. So the duplicated file name could be happen under `content/2018`. For the next year, I'll newly create `2019.org` under `content-org` with keeping `2018.org` as it is because I would like to keep each org file small as possible. In this case, as you mentioned, the duplication will not be happen because exported markdowns will be placed in different sub directories like `content/2018` and `content/2019`. This is good for me because, for instance, I can use the same file name for the posts on 1st, 2018 and 2019 like

```
content/2018/a-happy-new-year.md ;; 2018.org, ** an entry, EXPORT_FILE_NAME=a-happy-new-year
content/2019/a-happy-new-year.md ;; 2019.org, ** an entry, EXPORT_FILE_NAME=a-happy-new-year
```
And it is possible to access all posts written in 2018 as https://pxaka.tokyo/blog/2018/, this is also good for me.

Sorry for the confusing :(

BTW, I find out another way to avoid the duplication by assigning UUID for each `EXPORT_FILE_NAME`. It can be configured in `org-capture-templates` like [this](https://pxaka.tokyo/blog/2018/44febe88-04a5-9bc4-6bfb-678a8477a0ed/), uh-huh :)

**Comment by kaushalmodi** [comment]
> For this year, I'll put all my posts as subtrees in 2018.org under content-org directory. So the duplicated file name could be happen under content/2018

Wouldn't it be easier to move older (probably from 2017) posts to a subtree or a separate file where you set the HUGO_SECTION to 2017?

**Comment by kaushalmodi** [comment]
> Sorry for the confusing :(

No problem :)

> BTW, I find out another way to avoid the duplication by assigning UUID for each EXPORT_FILE_NAME. It can be configured in org-capture-templates like this, uh-huh :)

I have never used UUID. So today I learn :) But that link ends up too cryptic; difficult to remember (or even understand what that link would contain if someone bookmarks/saves that link.. like I would do in my notes Org file).

**Comment by takaxp** [comment]
Actually I read it yesterday, but I didn't dig it. For me, `org-hugo-slug` seems like a syntax checker and I should integrate it into my org-capture template! Thanks! really useful information :)

**Comment by kaushalmodi** [comment]
> For me, org-hugo-slug seems like a syntax checker

Hmm, I just updated it doc-string: https://github.com/kaushalmodi/ox-hugo/commit/6bb8a015001d970995f2d75165f65c5edcf4f36b. I think it should be better now :)

**Comment by takaxp** [comment]
Wow, thank you so much, clear for me :)

**Pull request merged**
