### PR TITLE
Copy file in the link description to the static directory

### PR DESCRIPTION
**Pull request by fvdbeek**
In a hyperlinked image like [this](https://ox-hugo.scripter.co/doc/image-links/#inline-image-also-hyperlinked-to-an-image) the link component is copied to the Hugo static directory, but the description component is not. This patch fixes this.

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Can you add a test case for this?

**Comment by fvdbeek** [comment]
I added a test that isn't very spectacular, because it is essentially the same example as in [Clickable image that opens the image](https://ox-hugo.scripter.co/doc/image-links/#inline-image-also-hyperlinked-to-an-image". I just changed the image in the link description to demonstrate that the file is actually copied to the static directory.

However, the test (`make -j1 test`) as mentioned in the Contributing Guide fails. If I understand it correctly that is because it compares the (changed) "content-modified" directory with the (unchanged) "content-golden" directory?

**Comment by kaushalmodi** [comment]
Hello, 

I am surprised that copying of files from your link descriptions doesn't work out of the box.

I just added this test ( https://github.com/kaushalmodi/ox-hugo/commit/73fd04fdecff04a47a633fc42b442e2a42a9fe75 ) that shows that this already works .. here's the message that gets printed when copying the image in the link description to static:

> [ox-hugo] Copied "/home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/elisp/ox-hugo/test/site/files-to-be-copied-to-static/static/images/unicorn-logo-small.png" to "/home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/elisp/ox-hugo/test/site/static/images/unicorn-logo-small.png"

Here's the updated HTML of that test: https://ox-hugo.scripter.co/test/posts/image-links/#clickable-image-that-opens-the-image--works

**Comment by fvdbeek** [comment]
Mmm. I did some more testing and it looks like it doesn't work if the path in the description contains whitespace. The problem is that the condition `(org-export-inline-image-p link org-html-inline-image-rules)` in `org-hugo-link` evaluates to nil. But I don't yet understand why.

**Comment by kaushalmodi** [comment]
>The problem is that the condition (org-export-inline-image-p link org-html-inline-image-rules) in org-hugo-link evaluates to nil. But I don't yet understand why.

How do I recreate that issue? By using any image file with space in the name? (Why would you do that! :))

**Comment by fvdbeek** [comment]
Why wouldn't you want spaces in filenames ;-) ? I stumbled upon the issue when I converted an old website with a lot of images with spaces in them.

I will provide a minimal example:

This org-file
```
#+hugo_base_dir: ../
#+hugo_section: test
#+title: Test

#+caption: Figure 1: test
#+name: Test
[[../files-to-be-copied-to-static/images/big/test image.gif][file:../files-to-be-copied-to-static/images/small/test_image.gif]]
```
is converted to this markdown:
```
+++
title = "Test"
author = ["Folkert van der Beek"]
draft = false
+++

<a id="org73cea7d"></a>

{{< figure src="/ox-hugo/test_image.gif" caption="Figure 1: Figure 1: test" link="/ox-hugo/test image.gif" >}}
```

But with a space in the path of the link-description:
```
#+hugo_base_dir: ../
#+hugo_section: test
#+title: Test

#+caption: Figure 1: test
#+name: Test
[[../files-to-be-copied-to-static/images/big/test image.gif][file:../files-to-be-copied-to-static/images/small/test image.gif]]
```
It is converted to this markdown:
```
+++
title = "Test"
author = ["Folkert van der Beek"]
draft = false
+++

<a id="org4bdfd37"></a>

[file:../files-to-be-copied-to-static/images/small/test image.gif](/ox-hugo/test image.gif)
```

**Comment by fvdbeek** [comment]
I tried to debug the issue, and it seems the problem lies in ox.el in stead of ox-hugo.el.
In the function `org-export-insert-image-links`, `(string-match link-re contents)` evaluates to nil if the link contains spaces. I haven't found an acceptable solution yet, and maybe the wisest solution is to just replace the spaces. But it should be possible to use image links with spaces, because such links *exist*.

**Comment by fvdbeek** [comment]
By the way, my proposed patch is indeed *not* the solution.

**Comment by kaushalmodi** [comment]
@fvdbeek Yes, I meant to break this "spaces in file" problem to a separate issue. So just did that.

> By the way, my proposed patch is indeed not the solution.

I am closing this PR then.

I do not yet have time to look into this; hopefully I can get to it this weekend. Thanks for the minimal example though. That will prove out to be useful.

**Pull request closed without merging**
