### PR TITLE
Add example Org file with org-ref style citations

### PR DESCRIPTION
**Pull request by kaushalmodi**
Ref: https://github.com/kaushalmodi/ox-hugo/issues/554

- [.csl file used by this test][1]
- [.bib files used by this test][2]

[1]: https://github.com/kaushalmodi/ox-hugo/blob/main/test/site/content-org/cite/csl/apa.csl
[2]: https://github.com/kaushalmodi/ox-hugo/blob/main/test/site/content-org/cite/bib/orgcite.bib

### CODE REVIEW

**Comment by jkitchin** [comment]
> @jkitchin I have spent more than an hour on this, but I believe I am missing something basic.
> 
> With [this minimal Org file](https://raw.githubusercontent.com/kaushalmodi/ox-hugo/1a0f1cafd66ec010efd340abcfc694a8f2bff589/test/site/content-org/citation-org-ref.org) in this PR, when I evaluate `(org-ref-process-buffer 'html)`, it puts NO_ITEM_DATA for all the citations even when I have the `bibliography: cite/bib/orgcite.bib` line, and the path is correct as well.
> 
> _See the generated .md in this PR. It has the same NO_ITEM_DATA for both citations._
> 
> All I did was evaluate
> 
> ```emacs-lisp
> (use-package org-ref
>   :ensure t)
> ```
> 
> to install `org-ref`. Is there any other minimal setup needed? I read through https://github.com/jkitchin/org-ref/blob/master/README.org#installation but I am possibly missing something important here.

I think you have a space in "bibliography: cite/bib/orgcite.bib" that breaks the link so there is no defined bibliography.

**Comment by kaushalmodi** [comment]
@jkitchin Thank you! That was it; removing the extra space after `bibliography:` fixed the problem.

**Comment by kaushalmodi** [comment]
- [ ] Update `org-ref` doc page in the manual

**Comment by kaushalmodi** [comment]
Org-ref info is added to https://ox-hugo.scripter.co/doc/org-ref-citations/.

**Pull request merged**
