### PR TITLE
Add additional example to users.toml

### PR DESCRIPTION
**Pull request by StevenTammen**

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Hello, I just checked your site source. Hopefully most of that YAML to Org style meta-data conversion was using a script :) 

Happy to know that you considered that effort worthwhile to switch to ox-hugo.

(And you didn't come across an ox-hugo bug in the whole process? Great! :D. But if you did face a bug or some anything for which you needed to do a workaround, feel free to open an issue.)

Thanks for sharing your site source.

**Comment by StevenTammen** [comment]
Hey, thanks so much for the nod. You commented on my repo a few months back and I finally got the time to refactor a bit. I'm planning on writing a blog post about this in the next couple days (which I can link), but I'll summarize here:

**Installing and stuff**

Installing ox-hugo was pretty straightforward. I use Spacemacs so followed the instructions for that. It wasn't working at first since I was running an older version of Org and hadn't updated my packages in a while. But when I did update, I was getting a weird error regarding wrong list types:

- [an example](https://github.com/org2blog/org2blog/issues/216)
- [another example](https://emacs.stackexchange.com/questions/14763/exporting-org-file-breaks-when-upgrading-to-orgmode-8-3)

Apparently if you have Org loaded when you update it can do strange things. I copied my .spacemacs, nuked my emacs.d, and recloned the Spacemacs project. After copying my .spacemacs back (and waiting for all the packages to get reinstalled), everything worked fine. All this is upstream from ox-hugo.

**Hugo TOC**

By far the most painful part of this process was dealing with the TOC autogenerated by Hugo (I was previously using a customized version of [bootstrap-toc](https://afeld.github.io/bootstrap-toc/) which was generating a TOC dynamically with Javascript). I decided that I wanted to generate a TOC at "export time" rather than "run time" (as it were), which meant using ox-hugo's Org TOC export, or sticking with Hugo's.

I had read [your page on this](https://ox-hugo.scripter.co/doc/org-toc/), and decided I didn't want any TOC showing up in the markdown. Unfortunately, the TOC generated by Blackfriday isn't very intelligent, and wraps everything in an extra `<li>` (i.e., `<ul><li> actual TOC stuff </li></ul>`). It also doesn't play nice with scrollspy out of the box. I am currently just regex-replacing the offending bits when I [include it in a partial](https://github.com/StevenTammen/steventammen.com/blob/master/layouts/partials/toc.html). I also had to tweak all the TOC CSS since it was expecting particular classes (as were generated with the Javascript). All this stuff took me the longest.

**Converting frontmatter**

I use four different sections (posts, pages, links, projects). I toyed with idea of writing scripts to automatically change the frontmatter, but I was manually changing many of the tags and categories anyway since I wanted to improve the organization of my content. So I ended up doing the replacements by hand and adding these tag/category changes as I went. If I had had more pages already I would have automated it. (Perhaps I will in the future for other people coming from YAML and TOML frontmatter -- it shouldn't be too hard).

**Exporting**

I wrote a simple bash script to invoke the export command for all the .org files in my org directory. I'm planning on setting up export-on-save today, which should work well for future pages.

**Image considerations**

The only place I had to go in and manually edit pages was with regards to images. I had previously just been including images with something like [[file:/path/to/img]] (which Goorgeous inlined without hyperlinks). I just updated them to image links [like how you explain](https://ox-hugo.scripter.co/doc/image-links/).


**Questions**

1) I had a few links to image files on the internet -- like [[https://mysite.com/path/to/img.png]] -- that Blackfriday was stalling on -- it was evidently making them [figures](https://www.w3schools.com/tags/tag_figure.asp). Export would complete eventually (after a long time), but the markdown inlined the images rather than linking to them as a URL. Do you know of a clean way to make [[https://mysite.com/path/to/img.png]] simply link to the URL rather than getting parsed by Blackfriday as some sort of image to be included?

2) I kept a page in markdown since it included HTML for a MailChimp form (see [here](https://raw.githubusercontent.com/StevenTammen/steventammen.com/master/content/projects/unicode-language-layers.md)). The styling wasn't working when I just wrapped that section with #+begin_html and #+end_html in Org. I may try to see if I can debug it more later today, but is this supposed to work? Is this how you embed HTML in Org?

Thanks!

-Steven

**Comment by kaushalmodi** [comment]
Hi Steven,

Thanks for the detailed writeup!

> Apparently if you have Org loaded when you update it can do strange things.  ..

Wow, you shouldn't have need to do the complete uninstallation/installation. But as Org is a huge beast and is available through various channels (ships with Emacs, via Org Elpa, Melpa, git), taming the `load-path` to get the version you want can be tricky. I had written a [detailed post][1] on how to deal with this.

> I had read your page on this, and decided I didn't want any TOC showing up in the markdown. 

I too wasn't quite a fan of that. But then ended up having both TOC styles (ox-hugo generated one shows on narrow width pages, Hugo generated one shows up on wide screens in sidebar [you can see that by narrowing/widening the browser when viewing the above linked post]).

> the markdown inlined the images rather than linking to them as a URL. Do you know of a clean way to make [[https://mysite.com/path/to/img.png]] simply link to the URL 

Yes! You'll need to put the same link as description too but **with `file:` prefix** :) See [this test][2]

> The styling wasn't working when I just wrapped that section with #+begin_html and #+end_html in Org.

I think you want `#+begin_export html .. #+end_export`. This is probably one of the Org changes going from v8.x to 9.x. [Test case for export block][3]

[1]: https://scripter.co/building-org-development-version/
[2]: https://ox-hugo.scripter.co/test/posts/image-links/#clickable-link-that-opens-the-image--works
[3]: https://ox-hugo.scripter.co/test/posts/export_block_html/

**Comment by StevenTammen** [comment]
These things worked. Thanks.

I'm having problems setting up the auto-save functionality. I am attempting add the following code to my .spacemacs in the user configuration section (as described on [this page](https://ox-hugo.scripter.co/doc/auto-export-on-saving/), but I can't get it to work.

```
(use-package ox-hugo
  :ensure t
  :after ox
  :init
  (defconst my/hugo-org-content-dir (expand-file-name "~/hugo_base_dir/content-org/")
    "Directory containing the Org mode posts.")

  (defun my/org-hugo-publish-current-buffer-as-post ()
    "Export the current Org file if a valid Hugo post.
Current file is exported using `org-hugo-export-to-md' if it
contains the #+title keyword and is present in the
`my/hugo-org-content-dir'."
    (let ((fname (buffer-file-name)))
      (when (and fname
                 (string-match-p (concat "\\`" (regexp-quote my/hugo-org-content-dir) ".*\\.org\\'")
                                 fname))
        (save-excursion
          (goto-char (point-min))
          (if (< (let ((case-fold-search t))
                   (how-many "^#\\+title:"))
                 1)
              (message "Unable to export as the Org file is missing the #+title keyword.")
            (org-hugo-export-to-md))))))

  (defun my/org-mode-hook-fn ()
    "My Org mode customization."
    (add-hook 'after-save-hook #'my/org-hugo-publish-current-buffer-as-post :append :local))

  (add-hook 'org-mode-hook #'my/org-mode-hook-fn))
```

I've tried replacing `~/hugo_base_dir/content-org/` with `~/hugo_base_dir/org/` (since I named the directory that contains org files `org/`), and also the absolute path of the directory (`C:\Users\steve\Desktop\Projects\steventammen.com\org`) -- I'm on Windows.

I don't know lisp basically at all, and I don't really understand what I need to do to get the code in the config file working. If I use the approach with

```
​* Footnotes
​* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# eval: (add-hook 'after-save-hook #'org-hugo-export-wim-to-md-after-save :append :local)
# End:
```

I can get the auto-export workflow working just fine. This is good for the short-term, but I'd like to just have one thing in my config file rather than adding that to all my source files, which are using the per-file structure.

Thoughts?

**Comment by kaushalmodi** [comment]
I haven't tested this on Windows. So the Windows style path could be a problem.. try this:

- Replace the whole `(concat ..)` argument of the `string-match-p` call with `"steventammen\\.com.*?org.+\\.org\\'"`.

**Comment by kaushalmodi** [comment]
Also, can you paste here what gets printed in the Messages buffer after you add this below the ` (let ((fname (buffer-file-name)))` line?:

```
(message "fname: %S" fname)
```

**Comment by StevenTammen** [comment]
Sorry to be dense, but do you mean

```
(use-package ox-hugo
  :ensure t
  :after ox
  :init

  (defun my/org-hugo-publish-current-buffer-as-post ()
    "Export the current Org file if a valid Hugo post.
Current file is exported using `org-hugo-export-to-md' if it
contains the #+title keyword and is present in the
`my/hugo-org-content-dir'."
    (let ((fname (buffer-file-name)))
      (when (and fname
                 (string-match-p ("steventammen\\.com.*?org.+\\.org\\'")
                                 fname))
        (save-excursion
          (goto-char (point-min))
          (if (< (let ((case-fold-search t))
                   (how-many "^#\\+title:"))
                 1)
              (message "Unable to export as the Org file is missing the #+title keyword.")
            (org-hugo-export-to-md))))))

  (defun my/org-mode-hook-fn ()
    "My Org mode customization."
    (add-hook 'after-save-hook #'my/org-hugo-publish-current-buffer-as-post :append :local))

  (add-hook 'org-mode-hook #'my/org-mode-hook-fn))
```

or

```
(use-package ox-hugo
  :ensure t
  :after ox
  :init

  (defun my/org-hugo-publish-current-buffer-as-post ()
    "Export the current Org file if a valid Hugo post.
Current file is exported using `org-hugo-export-to-md' if it
contains the #+title keyword and is present in the
`my/hugo-org-content-dir'."
    (let ((fname (buffer-file-name)))
      (when (and fname
                 (string-match-p (concat "steventammen\\.com.*?org.+\\.org\\'")
                                 fname))
        (save-excursion
          (goto-char (point-min))
          (if (< (let ((case-fold-search t))
                   (how-many "^#\\+title:"))
                 1)
              (message "Unable to export as the Org file is missing the #+title keyword.")
            (org-hugo-export-to-md))))))

  (defun my/org-mode-hook-fn ()
    "My Org mode customization."
    (add-hook 'after-save-hook #'my/org-hugo-publish-current-buffer-as-post :append :local))

  (add-hook 'org-mode-hook #'my/org-mode-hook-fn))
```

or something else?

**Comment by kaushalmodi** [comment]
Remove the parentheses from around `("steventammen\\.com.*?org.+\\.org\\'")` in your first snippet. 

I'm on phone, so being terse.

**Comment by StevenTammen** [comment]
Your suggestion worked. So this code works fine:

```
;; ox-hugo config, auto-export on save
(use-package ox-hugo
  :ensure t
  :after ox
  :init

  (defun my/org-hugo-publish-current-buffer-as-post ()
    "Export the current Org file if a valid Hugo post.
Current file is exported using `org-hugo-export-to-md' if it
contains the #+title keyword and is present in the
`my/hugo-org-content-dir'."
    (let ((fname (buffer-file-name)))
      (when (and fname
                 (string-match-p "steventammen\\.com.*?org.+\\.org\\'" fname))
        (save-excursion
          (goto-char (point-min))
          (if (< (let ((case-fold-search t))
                   (how-many "^#\\+title:"))
                 1)
              (message "Unable to export as the Org file is missing the #+title keyword.")
            (org-hugo-export-to-md))))))

  (defun my/org-mode-hook-fn ()
    "My Org mode customization."
    (add-hook 'after-save-hook #'my/org-hugo-publish-current-buffer-as-post :append :local))

  (add-hook 'org-mode-hook #'my/org-mode-hook-fn))
```

**Pull request merged**
