### PR TITLE
Export sub heading tags

### LINKED ISSUE #513: Enable exporting of sub-heading tags; recognize `#+options: tags:t`
Ref: https://github.com/kaushalmodi/ox-hugo/discussions/512

Export something similar to https://github.com/kaushalmodi/ox-hugo/discussions/512#discussioncomment-1943772 but with a div of tags exported soon after the markdown heading.

Recognize `org-export-with-tags` or `#+options: tags:t`

@stefanv

### PR DESCRIPTION
**Pull request by kaushalmodi**
Fixes #513

### CODE REVIEW

**Comment by kaushalmodi** [comment]
@stefanv Can you review the exported test Markdown in this PR: https://github.com/kaushalmodi/ox-hugo/pull/516/files#diff-5c147b0a0f1536f52a691a4e62bb133c60cf9642a2fabb3dd1b50fe62d86121b

**Comment by stefanv** [comment]
This is going to be very helpful, thank you @kaushalmodi.  I don't know if the non-breaking spaces between spans are standard—it may make it harder to style the output.  But it's not the end of the world if they cannot be avoided.  Maybe those should be wrapped in a span as well?

```<span class="whitespace-formatting">&#xa0;</span>```

A bit cluttery, but not sure how to get rid of them otherwise.

**Comment by stefanv** [comment]
Also, it looks like the tags may not be individually wrapped with `<span class="tag">...</span>`

**Comment by kaushalmodi** [comment]
>  I don't know if the non-breaking spaces between spans are standard—it may make it harder to style the output.

I just went with DRY and reused `org-html--tags`. The reasoning for non-breaking spaces is so that the list of tags doesn't wrap around to the next line.

Let me see if there's a better way.

**Comment by kaushalmodi** [comment]
@stefanv I agree with your point. Not that I am an HTML/CSS expert. But I don't see why `&#xa0;` is needed. I'll take that out because I see that we can easily do the formatting using CSS.

**Comment by stefanv** [comment]
@kaushalmodi I think this is almost there, but it's suboptimal not to have each tag wrapped in a span.  This way, we cannot create spacing between tags.

**Comment by kaushalmodi** [comment]
> but it's suboptimal not to have each tag wrapped in a span

I am confused.. this does wrap each tag in a span tag:

```html
<span class="tag">
  <span class="abc">abc
  </span>
  <span class="def">def
  </span>
  <span class="_abc_def_ghi">@abc def ghi
  </span>
  <span class="ghi_jkl">ghi-jkl
  </span>
</span>
```

---

> This way, we cannot create spacing between tags.

From https://ox-hugo.scripter.co/test/posts/sub-headings-with-tags/, we see that spacing is getting created between tags. I am using this CSS:

```css
         .tag span {
             background: lightgrey;
             font-size: small;
             padding: 0.1rem 0.2rem;
             margin: 0.2rem;
         }
```

**Comment by stefanv** [comment]
I was looking at an old diff :man_facepalming: Sorry for the noise.

**Pull request merged**
