### PR TITLE
Fix incorrect org-content link - robinwils.gitlab.io

### PR DESCRIPTION
**Pull request by Robin-Wils**
I often move my site from one platform to another lately, but I just found out that my content-org wasn't correct anymore, so I fixed it.

### CODE REVIEW

**Comment by Robin-Wils** [comment]
Ehm, you know what? Don't merge this yet. I think that I might move back to Gitlab soon, but I am not sure yet.

**Comment by kaushalmodi** [comment]
Haha, ok. Let me know when it's good to merge.

**Comment by Robin-Wils** [comment]
It is ready to merge. My source is at that location, but my result is on Gitlab. 

Although my domain might change soon. I am thinking of finally getting a own domain name, so maybe wait a day or two before merging. I could make a separate pull request for that of course, but I might as well put it in the same pull-request.

**Comment by kaushalmodi** [comment]
No problem. The merging can get. Getting a domain is a good idea.

**Comment by Robin-Wils** [comment]
Custom domain is set and link is updated : ).

**Comment by kaushalmodi** [comment]
Merged. Thanks!

**Pull request merged**
