### PR TITLE
Requesting to add shom.dev to real world examples list

### PR DESCRIPTION
**Pull request by shombando**

### CODE REVIEW

**Comment by kaushalmodi** [comment]
@shombando Thanks! I have merged this manually in https://github.com/kaushalmodi/ox-hugo/commit/adaf03c7bf73eabdb8469329a394b547691059e7

I wanted to refactor the commit with "doc(realworld)" prefix. (I am trying out an auto CHANGELOG generation flow for few days now 😃 )

**Comment by shombando** [comment]
@kaushalmodi that sounds cool, I'll be looking forward to how you implement it the auto changelog!

**Comment by kaushalmodi** [comment]
@shombando Like this https://ox-hugo.scripter.co/doc/changelog/#real-world-examples 😄

**Comment by shombando** [comment]
@kaushalmodi  looks great, good work mate!

**Pull request closed without merging**
