### PR TITLE
doc(realworld): Add https://idlip.github.io

### PR DESCRIPTION
**Pull request by idlip**
Learning and having fun is never ending love with emacs.

ox-hugo became one of the coolest package to make me fall in love with emacs more.

Thank you for making life easy ;)

### CODE REVIEW

**Comment by idlip** [comment]
I had only made pr as doc(realworld) , so edited by commit and forced pushed

**Comment by kaushalmodi** [comment]
Thanks for those kind words! I am glad you are finding ox-hugo useful.

**Comment by kaushalmodi** [comment]
@idlip Can you also set the `branch` value? I see that your repo doesn't use `main` branch as the default.

**Comment by idlip** [comment]
My bad, did not notice branch.

Updated!

**Pull request merged**
