### PR TITLE
Strip backslash from hugo shortcode and square bracket

### PR DESCRIPTION
**Pull request by hungpham2511**
Related to #336

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Thanks. I'll review and merge this this week.

**Comment by kaushalmodi** [comment]
If you can add a test with file: and image links for posts with Pandoc citations enabled, I can merge it quicker.

**Comment by hungpham2511** [comment]
Referring to https://ox-hugo.scripter.co/doc/contributing-guide/#contribute-to-code I can run `make -j1 test` without any issue, obtaining an exit code 0.

Just want to clarify, basically the test script loops through that results and ensure that the output .md remain the same, is that right? And to add a test, I need to add a snippet that "breaks" the compilation?

**Comment by kaushalmodi** [comment]
To add a test for your addition to the elisp, it will be useful to add an Org post example and the expected Markdown output.

**Comment by kaushalmodi** [comment]
Here's an example of such test addition: https://github.com/kaushalmodi/ox-hugo/commit/96e6bf01d2c0a267fbdd5b4105edb81b1cbaed0d

**Comment by hungpham2511** [comment]
Tests added. Please have a look. Do let me know if there is anything else I need to do.

**Comment by kaushalmodi** [comment]
Thank you for this PR.

**Pull request merged**
