### PR TITLE
Support cross-post linking for subtree-based exports

### PR DESCRIPTION
**Pull request by fvdbeek**
This PR adds support for cross-post linking in subtree-based exports (see #30). This isn't done by the strategy you proposed [here](https://github.com/kaushalmodi/ox-hugo/issues/30#issuecomment-374282119), but by preprocessing a snapshot of the org file, so the original org file stays unmodified.

To achieve this I have done the following:
1. split the rather complicated `org-hugo-export-wim-to-md` to three simpler functions (`org-hugo-export-file-to-md`, `org-hugo-export-all-subtrees-to-md` and `org-hugo-export-subtree-to-md`) in order to create a clearer distinction between the 'one-post-per-subtree' and 'one-post-per-file' flows.
2. added the function `org-hugo--preprocess-buffer` that creates an abstract syntax tree (AST) of the org buffer, checks the destinations of all "custom-id", "id" and "fuzzy" type links, changes them to file links if they point to a valid subtree outside the current one, and finally turns the modified AST into an org buffer. The buffer local variables are copied from the original buffer (modelled after `org-export--generate-copy-script` in `ox.el`). So the resulting buffer is a copy of the original, except for the cross-post links.
3. let the 'one-post-per-subtree' flows operate on the newly created preprocessed copy of the original buffer. The 'one-post-per-file' flow still operates on the original buffer.
4. added a workaround to enable the exporting of empty special blocks, because the parsing into an AST puts `nil` in the block.

I updated the test site:
- added some tests to the test site.
- included `(require 'org-id)` to `setup-ox-hugo.el` to handle links to :ID: properties  ("globally unique identifiers") in the test site.
- the testing revealed an indenting error in the test site under the "Verse for indentation" heading. The parsing into an AST (correctly) indented the example "Leading blank line followed by indented text", so the leading newline was followed by two additional spaces. This is corrected.
- changed some :CUSTOM_ID: properties to unique ones.

Any remarks are welcome.

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Wow! Thanks for this hefty PR. Please allow me few days to review it.. I might merge each commit in turn as I go through them. 

Before I do any of that, do you have your copyright assigned to FSF (I think I have already asked you this, but I need to be 100% sure before I merge this big PR)?

Big thanks!

**Comment by fvdbeek** [comment]
I have for my previous PR, but that was just a disclaimer for that one patch. So I will do it again, but now I will send an assignment for all future contributions. I should have done that the last time, but I didn't foresee this PR.

**Comment by fvdbeek** [comment]
I added support for cross-post links that jump to headlines by ID ([[id:...]] links) and by heading ([[*My heading]] links).

**Comment by fvdbeek** [comment]
I realize now that the `org-hugo--preprocess-buffer` function only checks the :EXPORT_FILE_NAME property to determine the filename of the link source and destination. This assumes all files are exported to the same section. Therefore, a check for the `#+hugo_section` keyword and the **:EXPORT_HUGO_SECTION** and **:EXPORT_HUGO_SECTION*** properties should be added. To construct the section path a variant of the `org-hugo--entry-get-concat` function is needed.

**Comment by kaushalmodi** [comment]
@fvdbeek Right, deriving the correct section name is really important. 

It's been a crazy work week so I haven't been able to yet do justice to your PR. 

I haven't checked, but if you use the Hugo `relref` shortcode for the internal links, you won't need the full section path (in most cases). Hugo auto-resolves based on just the page name, without any section prefixes, assuming that the page names are unique. Anyways very rarely you would have the exact same page names in 2 or more different sections.

**Comment by fvdbeek** [comment]
> @fvdbeek Right, deriving the correct section name is really important.
> 
> It's been a crazy work week so I haven't been able to yet do justice to your PR.
No need to hurry.
> I haven't checked, but if you use the Hugo `relref` shortcode for the internal links, you won't need the full section path (in most cases). Hugo auto-resolves based on just the page name, without any section prefixes, assuming that the page names are unique.
It isn't just about resolving the page name, but also about checking whether the link points to a destination within or outside the current subtree.

> Anyways very rarely you would have the exact same page names in 2 or more different sections.
Mmm, what about "index.md" in page bundles?

**Comment by fvdbeek** [comment]
Now the correct section paths are retrieved in the preprocessing buffer. The difficult part of this was to retrieve the `#+hugo_section` keyword, because the in-buffer settings are not yet set at this stage. Therefore, I had to retrieve it from the parse tree. This works, but it will break it is not placed near the top of the file or it is included using `#+SETUPFILE: filename or URL` syntax.

**Comment by fvdbeek** [comment]
Commit [108124b](https://github.com/kaushalmodi/ox-hugo/pull/280/commits/108124b79962ea19befced3b2a38a9502df2d018) uses an alternative strategy by copying the export settings from the original buffer to the preprocessing buffer, so the possible breakage in the previous commit should be fixed.

**Comment by fvdbeek** [comment]
If this PR is merged, the `ref` in stead of the `relref` shortcode should be used for cross-post links or files with the same name but in different sections will not be linked correctly.

**Comment by kaushalmodi** [comment]
@fvdbeek 

I am going through your PR piece by piece.

So far, I have merged your commits related to:

> split the rather complicated org-hugo-export-wim-to-md to three simpler functions (org-hugo-export-file-to-md, org-hugo-export-all-subtrees-to-md and org-hugo-export-subtree-to-md) in order to create a clearer distinction between the 'one-post-per-subtree' and 'one-post-per-file' flows.

---

Regarding:

> the testing revealed an indenting error in the test site under the "Verse for indentation" heading. The parsing into an AST (correctly) indented the example "Leading blank line followed by indented text", so the leading newline was followed by two additional spaces. This is corrected.

The earlier version was the intentional.. I mean to have a verse block in a plain list item.. not at the same level as the plain list item. But this exercise helped me fix a bug in ox-blackfriday.el. Thanks! :)

---

I'll go through the rest of your commits in the next week.

For future, feel free to open smaller PR's rebased to other other in-progress PR's.

**Comment by kaushalmodi** [comment]
@fvdbeek Looks like there was some oversight in my review of the "split org-hugo-export-wim-to-md .." commit, or in one of my refactoring commits after that.. `C-c C-e H H` stopped working.

For now, I have reverted those refactoring commits on master and have moved those to https://github.com/kaushalmodi/ox-hugo/tree/reorg-functions branch.

*Interestingly all the tests passed.. so I need a new test somewhere first.*

I'll revisit this first and merge the reorg-functions branch back into master and then get to reviewing the actual cross-linking commits.

**Comment by kaushalmodi** [comment]
@fvdbeek Hello, I finally reviewed your entire PR today.

There was a regression after the wim function reorganization --  C-c C-e H H did not work for Org files without valid subtrees (file-based exports).. I fixed that in https://github.com/kaushalmodi/ox-hugo/commit/29d818fd2ed2bb0e40c7611073a171d3a19b5c7a.

I then manually rebased and merged the commits related to cross-post link support in https://github.com/kaushalmodi/ox-hugo/commit/d2a91156ec1c2f29ae34c645a21ffaa721dcc58d.

I really appreciate your work on this!

Thank you.

**Comment by fvdbeek** [comment]
Excellent. I enjoyed it. I'm sorry for the late response. I was on a holiday with very limited connectivity.

Regards,
Folkert.

Kaushal Modi <notifications@github.com> schreef op 27 juli 2019 07:30:50 CEST:
>@fvdbeek Hello, I finally reviewed your entire PR today.
>
>There was a regression after the wim function reorganization --  C-c
>C-e H H did not work for Org files without valid subtrees (file-based
>exports).. I fixed that in
>https://github.com/kaushalmodi/ox-hugo/commit/29d818fd2ed2bb0e40c7611073a171d3a19b5c7a.
>
>I then manually rebased and merged the commits related to cross-post
>link support in
>https://github.com/kaushalmodi/ox-hugo/commit/d2a91156ec1c2f29ae34c645a21ffaa721dcc58d.
>
>I really appreciate your work on this!
>
>Thank you.
> 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kaushalmodi/ox-hugo/pull/280#issuecomment-515654073

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Pull request closed without merging**
