### PR TITLE
Add user dschrempf.

### PR DESCRIPTION
**Pull request by dschrempf**

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Awesome! Your blog source is a great example of using existing Org blogs for ox-hugo generated Hugo content! 

When you get a chance, also try out the subtree-based export. That will allow easier management of hierarchical tags and inheritance if common meta data (author, email, lang, etc). 

Thanks for sharing this.

**Comment by dschrempf** [comment]
Yes, you are right. I wanted to try the subtree based export, but with all the existing posts, it made more sense to go for a file based setup. At the moment, I use a snippet like system to create the files, but changing front matter items is inconvenient (because I have to use `sed` or something similar to go through all my files).

Thanks again for your work and also for this merge!

**Comment by kaushalmodi** [comment]
FYI, you don't have to strictly pick one flow vs other. I have a mix of file-based, subtree-based Org files and even raw Markdown files from older blog. You can see the scripter.co source on that Real World Examples page.  They all can exist together. 

So for newer posts, you can switch to subtree-based flow if you prefer that. Also look at the Org Capture setup in the Enhancements section on ox-hugo doc site. 

You are welcome! It's gratifying to see this flow work out not just for me :)

**Comment by kaushalmodi** [comment]
Regarding:

> front matter items is inconvenient (because I have to use sed or something similar to go through all my files).

If this is about adding/modifying common things to all files, looks into `#+setupfile` keyword in Org. You can have an Org file with just common meta data (author, email, export options, Org macros, etc), and you just include that using that keyword at the top of all files. You will find an example of that in my scripter.co source too.

**Pull request merged**
